### ISSUE TITLE
Cannot boot

### ISSUE THREAD

**Issue by twengtwinkie** [rrottmann/slax-efi#1]
Please post clear, concise instructions, with a paragraph showing how my installation should look after I am done.

**Comment by rrottmann** [comment]
Hi. Sorry for the late reply. I was on vacation and have just found some time to look into this.
I've used the iso file in a VirtualBox VM with 2048MB to boot a temporary test setup. /dev/sda was a 20GB disk that will be used to simulate a thumdrive.
I needed to adapt two directories so that the bootinst.sh script could be executed and removed the syslinux.efi file from a cp command as it got copied right before.
Then I powered off the VM and enabled EFI boot with it.
As you have suggested, I have added the final file-layout on the tumbdrive.
The exact procedure works also on physical systems with actual USB thumbdrive. I've found that some older systems have difficulties when using an USB3 thumbdrive to boot via EFI.
