### ISSUE TITLE
Some reason no drivers

### ISSUE THREAD

**Issue by ghost** [rrottmann/slax-efi#2]
I downloaded the EFI folder and placed it next to the slax folder. After that, the system started to boot on a computer with efi, but for some reason no drivers. This applies to both wi-fi and video drivers (instead of 1080p - put a lower: 480p and install above I have no way out).

On my computer, you can choose between efi and regular boot mode. In the boot menu, you can select this:
1) Windows
2) UEFI: Sandisk
3) Sandisk

And if you choose just Sandisk (without uefi), the drivers will be, but if you choose Uefi Sandisk - then no.

Hint, in addition to copying the EFI folder I had to make any other steps?

Translated with www.DeepL.com/Translator (free version)

**Comment by rrottmann** [comment]
So you placed the EFI directory together with your slax directory on a FAT32 formatted Sandisk usb drive and can boot with and without UEFI to slax but the system behaves differently?

Has your BIOS a setting to use Legay UEFI and Regular UEFI? Seems like the initramfs is not being loaded.

**Comment by ghost** [comment]
Here I made a video of what it looks like at me:
https://drive.google.com/file/d/1QOMJGjkSKcl98tdRlmk9q0nwySWAToIX/view?usp=sharing

**Comment by rrottmann** [comment]
That was very helpful!

So EFI boot works and the initramfs gets loaded. Otherwise the slax scripts would not work to load the additional .sb files.

At first I thought that vesamenu.32 maybe set the video card to a mode that prohibits the change of resolution later.
However this would not explain the missing wifi driver.

I found [this link](https://vovaprivalov.medium.com/fixing-problem-with-missing-wifi-adapter-on-ubuntu-18-04-dec50879a47e) and [this link](https://askubuntu.com/a/1020094) that suggests that UEFI and Secure Boot enabled might block third party modules.

Is there a setting in your BIOS to disable Secure Boot?

**Comment by ghost** [comment]
I have 2 devices: a computer and a laptop. The computer has this hybrid BIOS and the laptop has only UEFI installed.  

I want to tell the whole story:

With your EFI folder, I have managed to run Slax on my laptop. And when it turned on, I saw this low resolution screen. I thought that my new laptop (intel i5 1035g1) just didn't have any drivers because wi-fi wasn't turned on either.While I was trying to find a driver, I decided to check if the system was running from the computer in UEFI mode and then I was surprised that even the computer had such a low screen resolution. Also, wi-fi on the computer was not turned on (I use tp link 722). So I assumed that there is simply no part of the drivers if Slax is turned on in UEFI mode.

And here it is not at all clear, but with a strange frequency, wi-fi on a computer may not even start in normal mode (not uefi). The problem is solved by rebooting. Sometimes I have to reboot twice, sometimes 3. 

Now I tried again to run Slax on my laptop but I also connected my Wi-Fi adapter TP-link. And after a couple of reboots he found the wi-fi points using my adapter. So it is possible that the problem is just the lack of a driver for the built-in laptop adapter. And the low screen resolution is probably due to 
"At first I thought that vesamenu.32 maybe set the video card to a mode that prohibits the change of resolution later.
However this would not explain the missing wifi driver."

And about your question:
I have the "Secure Boot" turned off. If I turn it on Slax will not boot at all and the message "Secure boot fail" will appear on my screen.

**Comment by rrottmann** [comment]
Some wifi adapters need firmware loaded to them that. Maybe when you use Windows and reboot to Slax without hard-reset, the firmware is still loaded and you will get wifi working. I found [this](https://askubuntu.com/a/608350). Maybe that will help you troubleshooting it.

Upstream Slax creator Tomas Matejicek is working on a Debian 10 that will have more recent drivers. 

I usually connect a cheap USB wifi adapter in order to install additional firmware packages or prepare Slax in a virtual machine when I know which package I need to download before I boot it on a physical machine.

**Comment by ghost** [comment]
don't care about wi-fi)))
Is there any way to fix the screen resolution problem?

**Comment by rrottmann** [comment]
To rule out vesamenu.c32, it is possible to use menu.c32, a simple text menu.
A comparrison of lsmod and dmesg output can help to identify which modules are being loaded in both scenarios and whether a firmware does not load.

**Comment by shpaginkirill** [comment]
`
root@slax:~# lspci -nn
00:00.0 Host bridge [0600]: Intel Corporation Device [8086:8a12] (rev 03)
00:02.0 VGA compatible controller [0300]: Intel Corporation Device [8086:8a56] (rev 07)
00:14.0 USB controller [0c03]: Intel Corporation Device [8086:34ed] (rev 30)
00:14.2 RAM memory [0500]: Intel Corporation Device [8086:34ef] (rev 30)
00:14.3 Network controller [0280]: Intel Corporation Device [8086:34f0] (rev 30)
00:15.0 Serial bus controller [0c80]: Intel Corporation Device [8086:34e8] (rev 30)
00:16.0 Communication controller [0780]: Intel Corporation Device [8086:34e0] (rev 30)
00:17.0 RAID bus controller [0104]: Intel Corporation 82801 Mobile SATA Controller [RAID mode] [8086:282a] (rev 30)
00:1d.0 PCI bridge [0604]: Intel Corporation Device [8086:34b0] (rev 30)
00:1f.0 ISA bridge [0601]: Intel Corporation Device [8086:3482] (rev 30)
00:1f.3 Audio device [0403]: Intel Corporation Device [8086:34c8] (rev 30)
00:1f.4 SMBus [0c05]: Intel Corporation Device [8086:34a3] (rev 30)
00:1f.5 Serial bus controller [0c80]: Intel Corporation Device [8086:34a4] (rev 30)
01:00.0 Ethernet controller [0200]: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller [10ec:8168] (rev 15)
`

**Comment by shpaginkirill** [comment]
`root@slax:~# lspci -nn
00:00.0 Host bridge [0600]: Intel Corporation Device [8086:8a12] (rev 03)
00:02.0 VGA compatible controller [0300]: Intel Corporation Device [8086:8a56] (rev 07)
00:14.0 USB controller [0c03]: Intel Corporation Device [8086:34ed] (rev 30)
00:14.2 RAM memory [0500]: Intel Corporation Device [8086:34ef] (rev 30)
00:14.3 Network controller [0280]: Intel Corporation Device [8086:34f0] (rev 30)
00:15.0 Serial bus controller [0c80]: Intel Corporation Device [8086:34e8] (rev 30)
00:16.0 Communication controller [0780]: Intel Corporation Device [8086:34e0] (rev 30)
00:17.0 RAID bus controller [0104]: Intel Corporation 82801 Mobile SATA Controller [RAID mode] [8086:282a] (rev 30)
00:1d.0 PCI bridge [0604]: Intel Corporation Device [8086:34b0] (rev 30)
00:1f.0 ISA bridge [0601]: Intel Corporation Device [8086:3482] (rev 30)
00:1f.3 Audio device [0403]: Intel Corporation Device [8086:34c8] (rev 30)
00:1f.4 SMBus [0c05]: Intel Corporation Device [8086:34a3] (rev 30)
00:1f.5 Serial bus controller [0c80]: Intel Corporation Device [8086:34a4] (rev 30)
01:00.0 Ethernet controller [0200]: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller [10ec:8168] (rev 15)
root@slax:~# `

**Comment by ghost** [comment]
[dmesg.txt](https://github.com/rrottmann/slax-efi/files/5657191/dmesg.txt)
[driver.txt](https://github.com/rrottmann/slax-efi/files/5657192/driver.txt)
[lsmode.txt](https://github.com/rrottmann/slax-efi/files/5657193/lsmode.txt)

**Comment by ghost** [comment]
I really need your help!

**Comment by rrottmann** [comment]
It seems the issue with the GPU not detecting the maximum resolution is not only in slax:
https://gitlab.gnome.org/GNOME/mutter/-/issues/1434
https://lkml.org/lkml/2016/12/12/172

```
[   28.616270] nouveau 0000:01:00.0: unknown chipset (136000a1)
[   28.616273] nouveau: probe of 0000:01:00.0 failed with error -12
```
I suppose you have also a Nvidia graphics adapter in your notebook. So you might also try to install the nvidia driver:
https://linuxconfig.org/how-to-install-the-latest-nvidia-drivers-on-debian-9-stretch-linux

Is there a setting in the BIOS to select the main GPU? You could try to switch it to dedicated Nvidia GPU or Intel GPU packaged with the CPU. I think the switching between the two GPUs might be part of the issue.

Newer kernels might also help. So you should test with Debian 10 based slax. However I did not create a EFI for that.

**Comment by ghost** [comment]
This log is from a computer that runs the video card in normal mode (not efi) without any problems, it was visible on the video. I have the Nvidia 1060 installed on my computer. 

I did not drop the logs from my laptop, because in the beginning we need to figure out why the video card does not start in Efi mode on the same computer, but in normal mode - it starts.

**Comment by rrottmann** [comment]
Did you check `xrandr` as in one of the linked posts?

```
xrandr --newmode "2560x1080_60.00"  230.76  2560 2728 3000 3440  1080 1081 1084 1118  -HSync +Vsync
xrandr --addmode HDMI-1 2560x1080_60.00
xrandr --output HDMI-1 --mode "2560x1080_60.00" -v
```
Needs to be adapted to your supported resolutions.

**Comment by ghost** [comment]
```
root@slax:~# xrandr
xrandr: Failed to get size of gamma for output d
Screen 0: minimum 640 x 480, current 640 x 480, maximum 640 x 480
default connected 640x480+0+0 0mm x 0mm
   640x480       73.00* 

root@slax:~# xrandr --newmode "1920x1080_60.00"  173.00  1920 2048 2248 2576  1080 1083 1088 1120 -hsync +vsync
xrandr: Failed to get size of gamma for output default

```

i use dvi

**Comment by ghost** [comment]
probably somewhere efi mode does not start the video card. because without efi everything works on the same computer

**Comment by rrottmann** [comment]
Maybe it helps, when you [set a different screen resolution](https://wiki.syslinux.org/wiki/index.php?title=Menu#MENU_RESOLUTION) in `syslinux.cfg`?

```
MENU RESOLUTION 800 600
```
Can you specify in the BIOS whether to use internal or external GPU?

**Comment by ghost** [comment]
Motherboard Gigabyte H310MH BIOS F12 8A0FAG0P

I added the line "MENU RESOLUTION 1920 1080" and got this resolution, but it's not a solution because the video card never worked properly. 

In Bios I can choose which video card to use: "Processor integrated" or "PCi". I have always chosen "PCi". My Nvidia gtx 1060 graphics card is connected to my computer via PCI connector.

As you have seen on the video, I do not change anything in the BIOS. I just choose the boot method: "UEFI Sandisk" or "Sandisk". And if you choose UEFI Sandisk, the video card will not start. I showed you the Log of this boot. And if you choose normal mode (not UEFI Sandisk, just Sandisk), everything will work as it should.

**Comment by rrottmann** [comment]
Can you please switch to "Processor integrated" and try whether this works with UEFI?
Was the BIOS boot also using the nvidia GPU? Not sure whether the BIOS boot used the integrated GPU.

My guesses are:
* GPU switching is changed when using UEFI and you use the nvidia GPU where nouveau driver reports `nouveau: probe failed with error -12`
* or unsigned drivers cannot be loaded in UEFI mode (secure boot setting)
* or vesamenu.c32 initialized the GPU in a way that  prohibits the proper scan of capabilities later

Further troubleshooting options:
* You could try to install proprietary nvidia drivers, `savechanges` and exchange the then built initramfs.
* You could also try to boot a [Debian9 live iso](https://cdimage.debian.org/cdimage/archive/9.13.0-live/amd64/iso-hybrid/) in UEFI mode and see whether the GPU works there.
* Other options in order to see whether a different kernel would help:
   * try a [newer debian 10 beta](https://www.slax.org/blog.php)
   * or older slax version
* Maybe someone from the [slax google group](https://groups.google.com/forum/#!forum/slax-users) also tinkered around with UEFI boot and has a solution for this issue

Besides changing syslinux to use UEFI, I used vanilla slax and there should be no changes to kernel or initramfs that should affect the way how the hardware behaves.

**Comment by rrottmann** [comment]
Closing issue as EFI boot works and because I have no further idea about how to fix the display resolution issue.
