### ISSUE TITLE
secure boot support?

### ISSUE THREAD

**Issue by Darin755** [rrottmann/slax-efi#3]

**Comment by rrottmann** [comment]
Did not look into this, however I think that syslinux might not be a good choice for this. AFAIK, grub2 is the default option for Linux and secure boot.

https://wiki.debian.org/SecureBoot might be helpful.

**Comment by Darin755** [comment]
I have looked into setting up secure boot and have discovered that it is harder than it sounds. It should be easier when Slax 10 is released.

**Comment by rrottmann** [comment]
As Slax needs a customized kernel that needs to be signed in order to allow to boot from it, maybe a small, official Debian kernel could be used that boots a "trusted" stage where gpg signatures of the slax modules could be verified. Then `kexec` to Slax. This would use an already working secure boot environment and just extend it using gpg. Maybe the verification and the command to boot the next stage can be standardized so that this works universally?

Seems like https://www.rodsbooks.com/refind/installing.html#linux might also work. A boot manager handles then the secure boot and chainloads the configured bootloader. Config looks promising: https://www.rodsbooks.com/refind/configfile.html

**Comment by seba1452021** [comment]
https://github.com/seba1452021/slax-efi

+

https://github.com/seba1452021/slax-efi/discussions/1

**Comment by Darin755** [comment]
Closed old issue
